# Default Shwrap configuration
# Customize this file to specify which commands should be sandboxed

# By default, all namespaces (user, pid, network, ipc, uts, cgroup) are unshared
# Use 'share:' to selectively allow specific namespaces

# Example model/template
# base:
#   type: model
#   share:
#     - user        # Share user namespace with host
#   ro_bind:
#     - /usr
#     - /lib

# Example command configuration
# npm:
#   enabled: true
#   extends: base
#   share:
#     - network     # Allow network access
#   bind:
#     - ~/.npm:~/.npm
#     - $PWD:/workspace
